### ISSUE TITLE
Update video.js to latest version

### ISSUE THREAD

**Issue by naclander** [nextcloud/files_videoplayer#11]
The latest version of video.js is[ 5.13.2](https://github.com/videojs/video.js/blob/master/CHANGELOG.md), and it seems we are using an arbitrarily older version ( 4.12.11 )

I am wondering if a) there is a specific reason we are using such an old version and b) is there a plan to update video.js to the latest version

**Comment by Instagit** [comment]
The [skin](https://github.com/cabin/videojs-sublime-skin), which I think was an important reason to make the switch to this player, [is not compatible](https://github.com/cabin/videojs-sublime-skin/issues/12) with the latest video.js version. There's a link to an [adjusted version](https://codepen.io/zanechua/pen/GozrNe), but that would also need some work as it still has some issues.

**Comment by Instagit** [comment]
I'm looking to replace Video.js with MediaElement.js, which now has better default functionality. :point_right:  https://github.com/nextcloud/files_videoplayer/issues/20

**Comment by jancborchardt** [comment]
@Instagit just make sure that the project is active and properly maintained, and also compatible with all the relevant media file types which worked before. :)

**Comment by Instagit** [comment]
Yeah, of course. I'm looking to make this a general improvement. Breaking working features is not acceptable. ;)

**Comment by jancborchardt** [comment]
So in any case, let’s postpone this to Nextcloud 13 as we are in feature freeze. :) As soon as Nextcloud 12 is released we can experiment here.

**Comment by naclander** [comment]
Hey @Instagit ,

Why was this issue closed? We're still on the same version of video.js no?

**Comment by Instagit** [comment]
@naclander 
Sorry, I missed that this was added as a milestone. It would make more sense to add https://github.com/nextcloud/files_videoplayer/issues/20 instead as that's what we were referring to. 

Updating Video.js, i.e. this issue, probably won't be solved as it's pointless to invest work in fixing all the CSS for the new Video.js version when we're looking to use another player in the future.

**Comment by naclander** [comment]
@Instagit Makes sense, thanks for the reply.
