### ISSUE TITLE
the mkv file can not play with music

### ISSUE THREAD

**Issue by AndyMephisto** [nextcloud/files_videoplayer#132]
I can play video by mkv type file, but the status of the volume button is disable

**Comment by Instagit** [comment]
Can you upload a file that doesn't work?

MKV support is a hack, it's not officially supported.

**Comment by AndyMephisto** [comment]
Sorry, I just have one mkv file that is too big to upload. I hope some file infos could help you to figure out the problem, here is the thing:

Video:
resulation: 1280 x 690
frams: 23.98f/s
bit rate: 448kbps

Audio:
bit rate: 448kbps
channel: 6
audio sampling rate: 48.000kHz

If you want more information, you can try to download it

Sharing URL:  http://cloud.gaoxinyu.cn:5010/s/58R7e9pjtym9Twi

Thanks a lot  : )

**Comment by mffan0922** [comment]
Hi all, I encountered the same problem that My volume button is disabled, example file is https://nextcloud.mffan0922.top/index.php/s/XqgLzotGZP2Njpx, hope for your reply, thanks a lot!

**Comment by mffan0922** [comment]
> Hi all, I encountered the same problem that My volume button is disabled, example file is https://nextcloud.mffan0922.top/index.php/s/XqgLzotGZP2Njpx, hope for your reply, thanks a lot!

I'm sorry, Just now I tried again on my company's PC, It works, so it is probably my own computer's problem. Just don't know why

**Comment by mffan0922** [comment]
> > Hi all, I encountered the same problem that My volume button is disabled, example file is https://nextcloud.mffan0922.top/index.php/s/XqgLzotGZP2Njpx, hope for your reply, thanks a lot!
> 
> I'm sorry, Just now I tried again on my company's PC, It works, so it is probably my own computer's problem. Just don't know why

Sorry again, new found!! 
I open the vedio in my share link, the sound button can be tuned but no sound, and when I open in my own nextcloud, the sound button is disabled, anybody help?

**Comment by AndyMephisto** [comment]
> > > Hi all, I encountered the same problem that My volume button is disabled, example file is https://nextcloud.mffan0922.top/index.php/s/XqgLzotGZP2Njpx, hope for your reply, thanks a lot!
> > 
> > 
> > I'm sorry, Just now I tried again on my company's PC, It works, so it is probably my own computer's problem. Just don't know why
> 
> Sorry again, new found!!
> I open the vedio in my share link, the sound button can be tuned but no sound, and when I open in my own nextcloud, the sound button is disabled, anybody help?

same problem!!!! totaly same!

**Comment by Instagit** [comment]
> > Hi all, I encountered the same problem that My volume button is disabled, example file is https://nextcloud.mffan0922.top/index.php/s/XqgLzotGZP2Njpx, hope for your reply, thanks a lot!
> 
> I'm sorry, Just now I tried again on my company's PC, It works, so it is probably my own computer's problem. Just don't know why

Are you using different browsers at work and at home? I can't access the link you posted, but my guess is that the audio format is supported by one browser but not the other.

**Comment by mffan0922** [comment]
> > > Hi all, I encountered the same problem that My volume button is disabled, example file is https://nextcloud.mffan0922.top/index.php/s/XqgLzotGZP2Njpx, hope for your reply, thanks a lot!
> > 
> > 
> > I'm sorry, Just now I tried again on my company's PC, It works, so it is probably my own computer's problem. Just don't know why
> 
> Are you using different browsers at work and at home? I can't access the link you posted, but my guess is that the audio format is supported by one browser but not the other.

Sorry I deleted the file already. But I do use the same browser **as the latest chrome**. The file's format is .mkv and as I described before, **I open the vedio in my share link, the sound button can be tuned but no sound, and when I open in my own nextcloud, the sound button is disabled**

**Comment by Instagit** [comment]
I need to see the video :)

Can you upload it to some file sharing site?

**Comment by mffan0922** [comment]
> I need to see the video :)
> 
> Can you upload it to some file sharing site?

https://rustle.cc/nextcloud/index.php/s/2QCAQBTxFtgBJcM
This is the file whichI uploaded it last night

**Comment by mffan0922** [comment]
> I need to see the video :)
> 
> Can you upload it to some file sharing site?

https://rustle.cc/nextcloud/index.php/s/2QCAQBTxFtgBJcM
This is the file which I uploaded last night.

**Comment by Instagit** [comment]
>Stream #0:1: Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s (default)

That audio format is not supported by browsers.

https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

**Comment by mffan0922** [comment]
> > Stream #0:1: Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s (default)
> 
> That audio format is not supported by browsers.
> 
> https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

Oooh, fine, I see thanks
