### ISSUE TITLE
The video player does not load the srt file.

### ISSUE THREAD

**Issue by codelabinf** [nextcloud/files_videoplayer#142]
Server version 17.0.0.9

Expected behaviour

subtitle options show up on the video player
Actual behaviour
I have some video along with its subtitle but the video player app does not load the srt file.
Steps to reproduce

Open a video .mp4 from a folder that contains a srt file with same name + es.srt
1   video.mp4 and video.es.srt
2  Play the video
3  Subtitle is not available

Is there any solution?
Thank you

**Comment by Instagit** [comment]
https://github.com/nextcloud/files_videoplayer/issues/133

The video player doesn't have support for subtitles.
