### ISSUE TITLE
Cannot play MP4 video

### ISSUE THREAD

**Issue by ZehuanZhang** [nextcloud/files_videoplayer#147]
### Expected behaviour
Tell us what should happen
the video player should play MP4 video normally (play frames with sound)

### Actual behaviour
Tell us what happens instead
only normally sound with black background.

### Steps to reproduce
1. tansfer a MP4 video file to nextcloud, this mp4 infomation is:
General
Complete name                            : C:\Users\***\***.H265.mp4.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/mp41)
File size                                : 531 MiB
Duration                                 : 44 min 57 s
Overall bit rate                         : 1 652 kb/s
Writing application                      : Lavf58.20.100

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main@L3.1@Main
Codec ID                                 : hev1
Codec ID/Info                            : High Efficiency Video Coding
Duration                                 : 44 min 57 s
Bit rate                                 : 1 518 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.066
Stream size                              : 488 MiB (92%)
Codec configuration box                  : hvcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 44 min 57 s
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 41.3 MiB (8%)
Default                                  : Yes
Alternate group                          : 1

2. Open WEB client, click video file(open video player)
3. Video player is poped, play sound normally but without any frames

**Comment by Instagit** [comment]
Your browser probably doesn't support the H265 codec.

https://caniuse.com/#feat=hevc

**Comment by ghost** [comment]
https://github.com/nextcloud/files_videoplayer/assets/121665846/d0bff95a-6162-465f-b6b3-6a14e429790b
