### ISSUE TITLE
Video format extending H264

### ISSUE THREAD

**Issue by trecords** [nextcloud/files_videoplayer#148]
Hi All, and thanks for this nice feature in nexcloud)

I dont have issue but I need feature which videojs already supports. videojs support many file formats and also H264 video format but I was not able to make these files work with nextcloud plugin. My files are directly from CCTV cameras and they are with dav extension.
I think that if videojs supports H264 format then that would be easy to just integrate and add .dav video extension into support list. Please Advise.

Regards,
Turkel.

**Comment by Dragon988** [comment]
But it does support H264...

**Comment by Instagit** [comment]
H264 is definitely supported. If there's a problem with it, we need more information.
