### ISSUE TITLE
Looks like video player don't show up with a shared folder

### ISSUE THREAD

**Issue by Aurnytoraink** [nextcloud/files_videoplayer#150]
### Expected behaviour
Suppose to play the video in the web browser

### Actual behaviour
When the user share a folder containing a video via a link, the video player don't come and instead the user is invited to download the file

### Steps to reproduce
1. Upload a video in a folder
2. Get a shared link of the folder
3. Paste it into another website and try to play a video

**Comment by mhoeher** [comment]
I can confirm this. In my company, we have an internal NextCloud instance set up and wanted to create a shared folder with videos as a kind of poor man's YouTube replacement:

* When we use a public share link, videos are not playing.
* However, when we create an internal share link, things work as expected.

For the time being, using the internal share link is an okayish workaround for us, however, it'd be cool if public ones would work as well ;-)

**Comment by skjnldsv** [comment]
Fixed by #152
