### ISSUE TITLE
Unable to play .mkv or .avi

### ISSUE THREAD

**Issue by tuytuy** [nextcloud/files_videoplayer#17]
# Expect behaviour

Just like the mp4 files the video would play in the videoplayer

# Actual Behaviour

When a .avi or .mkv file is clicked it downloads

**Comment by naclander** [comment]
FWIW, I posted a [similar issue](https://github.com/nextcloud/files_videoplayer/issues/9) a while ago, which was closed.

I am unable to play .mkv or .avi files on linux in the browser on either chromium, or firefox. 
I did notice .mkv files played fine when I was testing this on Safari on macOS, but I no longer have access to this OS so I can't debug further.

**Comment by Instagit** [comment]
The AVI container format is not supported by browsers. Same for MKV, but it is very similar to WebM so many MKV files should work.

Without the files I can't look into it further, but so far all these issues were due to lack of browser support.

**Comment by Instagit** [comment]
MKV support was added some time back and should work in most environments. It depends on the browser and operating system you are using.

AVI support probably won't be happening, because browsers don't support it.
