### ISSUE TITLE
Video player updates

### ISSUE THREAD

**Issue by Instagit** [nextcloud/files_videoplayer#20]
There have been some feature requests like keyboard shortcuts, subtitle support, video library updates that are a bit difficult to do with the current player, because it relies on an extension for the skin that doesn't work with the current Video.js version and it would also rely on extensions for the new features.

So I looked around a bit and found that [MediaElement.js](https://github.com/johndyer/mediaelement) had a major update that overhauled the default style and added all those features by default.

![output](https://cloud.githubusercontent.com/assets/2681794/22557312/7ee6b760-e96a-11e6-902e-0eb35f23cd47.gif)

* **Default styling looks good, no need for an extension.** The style looks very similar to the current player, but adds a few required features and is very easy to customize (you can add/remove features with a parameter).
* **Keyboard shortcuts work by default** (play/pause, forward/back, fullscreen).
* **Current/total time display.** This is somewhat lacking in the current player, especially for long videos.
* **Show buffer position** to see how much of the video has loaded.
* **Subtitles and subtitle switching.** I figured out how to make subtitles work, with the current player or MediaElement.js. I'd need some help with the implementation, but it shouldn't be too difficult. MediaElement.js has the added bonus that it offers UI elements to enable/disable subs or switch between them.
* Playback speed can be changed. I don't know if it's really needed, but it has been asked for a few times.
* Same license (MIT)

I created a [demo branch](https://github.com/nextcloud/files_videoplayer/tree/mediaelement) with the MediaElement.js player if you want to check it out. **It's not release ready at all**, only a test to check if it works.

Personally, I'd prefer to go with this player in the future as it has more features by default and makes updates easier. Please tell me what you think.

**Comment by Instagit** [comment]
@jancborchardt @LukasReschke @MorrisJobke

**Comment by MorrisJobke** [comment]
I really love this. I gave it a quick try and it works really nice 👍

**Comment by MorrisJobke** [comment]
Thanks a lot @Instagit

**Comment by Instagit** [comment]
>the grey bar at the right of the video, is that a scrollbar?

No, it's unoptimized CSS, because I just threw this together for quick testing. :)

>the spinner should be adjusted to be the class="loading" spinner we use everywhere

Ok. I don't have much time right now, but when I do I'll work on this.

**Comment by enoch85** [comment]
Any update here @Instagit?

**Comment by Instagit** [comment]
No, I haven't had time to work on it.

**Comment by Instagit** [comment]
Update:

I'm waiting for a few issues to be addressed in the MediaElement player:

https://github.com/mediaelement/mediaelement/issues/2342
https://github.com/mediaelement/mediaelement/issues/2346
https://github.com/mediaelement/mediaelement/issues/2347

Then there's a content security policy error when changing the volume that needs to be looked at. Other than that, the player is now in a working state and I think can be tested soon.

I'll try adding subtitle support when the other issues are fixed.

**Comment by enoch85** [comment]
Wow! Ditch Plex, go Nextcloud all in! :D

**Comment by Instagit** [comment]
The demo branch is now ready to be tested.

https://github.com/nextcloud/files_videoplayer/tree/mediaelement

New features:

* show times (current, total and when hovering the mouse over the timeline)
* make volume is easier to adjust precisely (there's still the content security policy error when setting it with the mouse, but it works)
* player shows how much of the video is buffered
* scrubbing works
* allow everything to be controlled with the keyboard

| Function   | Key           |
| ------------- |:-------------:|
| seek | left/right arrow keys |
| volume | up/down arrow keys |
| fullscreen | F |
| exit | ESC |

They UI is similar to the current player and, in my opinion, still minimal and unobtrusive.

**Comment by jancborchardt** [comment]
@Instagit awesome! Am mobile atm, but did the issue with the grey element and using our proper spinner work out? :)

**Comment by Instagit** [comment]
The line on the right side is now black and looks exactly the same as in the current player. I think it happens because the video player calculates the element size at fractions of a pixel and depending on the window and video size it causes display errors. At full size, I can fix it by changing the max-width, but it'll still happen at certain smaller sizes and it's different depending on the browser.

The spinner in the player uses CSS animations, the Nextcloud one is an animated GIF. I think it would be easiest if a designer could replace the spinner in these files:

https://github.com/nextcloud/files_videoplayer/blob/mediaelement/mediaelement/mejs-controls.png
https://github.com/nextcloud/files_videoplayer/blob/mediaelement/mediaelement/mejs-controls.svg

**Comment by Instagit** [comment]
Actually, I have all I need to implement subtitles... let's see. This example is hardcoded. :wink:

![subs](https://user-images.githubusercontent.com/2681794/29415290-e4872e78-8362-11e7-96f3-228076fcce9a.png)

**Comment by jancborchardt** [comment]
@rullzer @LukasReschke can you comment on @Instagit’s question about the `/remote.php/webdav` file URL?

**Comment by rullzer** [comment]
`/remote.php/webdav` is the old webdav path. New path is `remote.php/dav/files/<username>`

**Comment by Instagit** [comment]
Alright, I'm done with the changes for now. Please take a look at the player and see if you find any issues.

![mediaelement](https://user-images.githubusercontent.com/2681794/29671441-d7c945f4-88e9-11e7-92b2-6e131c10dca9.png)

Running version 13 Alpha, the path information I get using JS is still in the old format so I'd keep it like that for now.

The other issue I already mentioned is the Content Security Policy error when changing the volume with the mouse. It would be nice if someone could look at that, because I can't find what causes it.

**Comment by jancborchardt** [comment]
@LukasReschke can you help about the issue with Content Security Policy?

**Comment by robbiewu007** [comment]
@Instagit Tested Nextcloud 12.0.3, worked just as it with Microsoft EDGE, IE11, Safari on iOS11, but broken with Chrome 62.0.3202.62， Click the video file first time, nothing happened, then click again, a default HTML5 play display with NO Close 'X' button on the right-upper corner, can NOT close the video play anymore.

**Comment by Utshox** [comment]
@Instagit Tested Nextcloud 12.0.3. i'm facing problem with subtitles. cc button is showing like a second and then its gone. what could be the problem?

**Comment by jancborchardt** [comment]
@nextcloud/javascript could you also help here? :)

**Comment by Sraw** [comment]
How is it going now? I'm looking for it.

**Comment by Instagit** [comment]
About the problems with Nextcloud 12: Is it even planned to backport the new player to old versions? If so, I need to know how to jump between Nextcloud versions for development. Right now, I'm only using Nextcloud 13 Alpha.

**Comment by MorrisJobke** [comment]
> About the problems with Nextcloud 12: Is it even planned to backport the new player to old versions? If so, I need to know how to jump between Nextcloud versions for development. Right now, I'm only using Nextcloud 13 Alpha.

```
git checkout v12.0.3
git submodule update
```

Done ;)

**Comment by MorrisJobke** [comment]
And you need to maybe reinstall, because a downgrade is not supported.

**Comment by nsrosenqvist** [comment]
Has this update been released yet? If not, can I find and test the branch somewhere?

**Comment by enchained** [comment]
@nsrosenqvist I think this is the branch: https://github.com/nextcloud/files_videoplayer/tree/mediaelement

However, I couldn't test the player myself - I had troubles installing nextcloud v13 beta via the docker, or upgrading to it, and I decided to wait for v13 release to test, and now I found out it is supposed to release by the end of the month, so thanks for reminding.

@Instagit Will this player version be able to support custom user plugins? I heard there are plugins for mediaelement and I'd like to make one with subtitles word dictionary lookup.

**Comment by Instagit** [comment]
Yes, that's the branch.

@enchained I don't see why not, but I haven't tested plugins myself, as that's exactly what we're trying to move away from.

**Comment by nova168168** [comment]
not work with my Nextcloud  , version 12.0.4. After replace the files , I can't login the system and it shown that the videoplayer is not compatible version. How to check ?

**Comment by Instagit** [comment]
@nova168168 Try setting the min version in info.xml:
https://github.com/nextcloud/files_videoplayer/blob/mediaelement/appinfo/info.xml#L26

**Comment by nova168168** [comment]
@Instagit I try to modify the min version to 12 or 13 , it can login to the Nextcloud system but when I play the video, it still shown the old version videoplayer interface ! why ?

**Comment by Instagit** [comment]
Could you open a new ticket for this? I want to keep this one for the development of the video player. I'll delete the posts once the new ticket is open. Thank you.

**Comment by batu-one** [comment]
Running this on Nextcloud 13 and it's great! I came across a few issues though:
* On iOS, when I press play, the native video player goes into full screen which makes the subtitles disappear. Don't know about Android...
* On desktop, the subtitles stay small in full screen. I'm zooming in with cmd+ or ctrl+ as a workaround now.
* When a video in a folder shared by a link is accessed while not logged in, an authentication dialog appears.
* Subtitles don't work in folders shared by link.

**Comment by rcmz** [comment]
Hi, I tested the branch in 13.02 and it's promessing but kinda half broken :

**Comment by rcmz** [comment]
Hi, I tested the branch in 13.02 and it's a mixt bag :

**Comment by rcmz** [comment]
Hi, I tested the branch in 13.02 and it's a mixt bag:

On firefox desktop it works great.
On firefox mobile the player launches but in a broken fullscreen way, controles are not accessible.
On Chrome desktop or mobile the default HTML5 player lauches and it is half  broken.

I haven't tested subtitles but I don't there are top priority right now.
Do you have ideas on how to improve this ?

**Comment by Refhi** [comment]
Hi,
it looks like it's the right place to suggest an audio track selection option ?
If not please tell me I'll delete my post and open a ticket.

**Comment by Instagit** [comment]
@Refhi Good idea, but I don't think the player (MediaElement.js) supports it right now.

**Comment by Instagit** [comment]
Here's a list of things that need to be done for me to consider the player ready for release:

- [ ] Implement scaling when video dimensions are bigger than the window size.
- [ ] Fix CSP error on volume change with the mouse.
- [ ] Adjust UI elements to fit the Nextcloud style if necessary.
- [ ] Backport patches from the current player.
- [ ] Test in Chrome, Firefox and Edge on desktop and mobile devices

Any help with this is appreciated.

**Comment by emilsl93** [comment]
Sorry - I´m no developer, but i just have to ask. Will this new and updated video player app enable support for playing videos recorded in HEVC codec? (Samsung S9+) because i only get a black screen when playing HEVC encoded videos in the web-interface using latest Chrome. running Nextcloud 14.0.3
cheers!

**Comment by Instagit** [comment]
@emilsl93 Video support depends on the browser, not the video player. You can check which browser supports it [here](https://caniuse.com/#feat=hevc).

**Comment by maartenw8** [comment]
Great work! However, the CC button dissapears after less then a second. Is there any way to fix this issue?

**Comment by voxdemonix** [comment]
This thread will soon enter his third year.
Do anybody has a possible date (+-) for a release ?
Is there still a dev ?

**Comment by lazniak** [comment]
Hi I'm using Nexcloud 15. it is possible to instal the update visible in post from 2 Feb 2017 - with displaying times and some new features to my nexcloud? if yes? please explain a little how. I tried many times and always I have info about compatibility - that it was wrote for nexcloud 13 version? could you help me?

**Comment by pjrobertson** [comment]
@Instagit just seen this as I was looking for a `Current/total time display` in the player.

This update seems impressive, with so many new features! Can I suggest an initial release be made with what you proposed in your first post, so that we can start making use of some of these awesome features? Perhaps just:

1. keyboard shortcuts
2. Current/total time display
3. buffer display.

I'm assuming these will cover 90% of what people want. If you think it's worth it, I can jump into the code and start commenting out any of the features not in the list above with `#TODO` and then packaging for a release.

Let me know your thoughts!

**Comment by rullzer** [comment]
Hi all.

We recently updated the video player to the latest version. As well as some other improvements.
If anybody wants to work on these features now that we have webpack and more up to date code PRs would be more than welcome!

**Comment by brzd** [comment]
Hi! Where is the latest release available at? Could this be added to apps within nextcloud?

**Comment by brzd** [comment]
Hi! Where is the latest release available at? It seems files here are older? Could this be added to apps within nextcloud?

**Comment by KiritoStudio** [comment]
@brzd I have pushed a pull request to support the arrow keys, although not merged yet. You can also clone my repo(https://github.com/KiritoStudio/files_videoplayer) and have a try.

**Comment by tsuihak** [comment]
I have the nextcloud installed on RPi2. I am watching videos remotely and there is an option of subtitles and audio switching. How do I proceed to enable this?

**Comment by Instagit** [comment]
Status of this new video player:

Since the Nextcloud team has updated the current player, I guess this isn't needed or wanted anymore. I don't have much time to work on it anyway. Should my company require extra features, I might continue development and turn it into a Nextcloud app - the same way the current video player was created. ;)

If anyone wants to continue development, the code is there to be used.

I'll close this ticket and will move the mediaelement branch to my own repository soon. I'll post a link here then.

**Comment by voarsh2** [comment]
I haven't tried this, but this looks pretty neat - Nextcloud is my Google Drive replacement and I think video player is really lacking in Nextcloud
