### ISSUE TITLE
[Feature Request] Remember/Save Playback Position across devices

### ISSUE THREAD

**Issue by carlocapocasa** [nextcloud/files_videoplayer#22]
I'm using Nextcloud to store my documents and consume video, audio and text.

It would tremendously increase the value of my entire Nextcloud usage if the video player would remember the playback position in a video, and store it in some kind of metadata on the server.

That way, I could do my tremendously enjoyable "grab my phone and keep watching in the bathroom" routine that I already practice on commercial services like Youtube and Netflix to great effect.

On a more serious note, this is the one commercial cloud feature that that I still haven't been able to replicate with a DIY solution in any way.

I don't think this would necessarily lead to more and more feature requests trying to transform nextcloud into a video player like [Streama](https://github.com/dularion/streama). It's just a simple future standard feature that comes naturally for any cloud video player.

**Comment by Instagit** [comment]
I don't like when video players do that and for my purpose it would make the player unusable. :wink: Customers look at videos, share the access and when someone else looks at it, it needs to start from the beginning. For personal use, nothing I enjoy watching on a big screen would do on mobile. That's all a matter of usage and opinion of course.

That being said, I only help out with the video player and Nextcloud is not my project. I don't know if there's a better place on Github for Nextcloud feature requests, but you could try IRC to make your voice heard. Not sure the main Nextcloud team will see it here.

**Comment by carlocapocasa** [comment]
Well yeah you'd have to implement it so it doesn't get in a way and isn't a privacy problem. Remembering the position by-user would do that, so for a public video the behavior wouldn't change.

Thanks for the pointer, I started a thread over in the [forum](https://help.nextcloud.com/t/remember-playback-location/8533).
