### ISSUE TITLE
a place for Videos as smae for "Music" app

### ISSUE THREAD

**Issue by mckaygerhard** [nextcloud/files_videoplayer#23]
### Expected behaviour
See a "Videos" place in menu same as "Music" or "Gallery" does..

### Actual behaviour
no "Video" place in menu, only "Music" and "gallery" ..

How could i put a "Videos" icon on menu when i enabled this plugin, i'll try to follow the same for "Music" app but not lucky..

i'm not coder or programer, so please explain me, i know some of php...

**Comment by Instagit** [comment]
I think the main problem is that generating preview images for videos is more difficult than for images. It requires additional software to be installed on the server to read the video files and generate thumbnails.

When that problem is solved, I'm sure there will be a video gallery.

**Comment by mckaygerhard** [comment]
hi @instagit i'm not interesting in the "preview" only in:
a) how can put a button that said "Videos"
b) that button only will display video files

i mean filter all the videos only by click that button.. like music does! 

about the preview, no preview was made for music files, and play videos its good as it today

**Comment by Instagit** [comment]
I guess you can take a look at the [audio player app](https://apps.nextcloud.com/apps/audioplayer) and see  how they do it. It's open source. I can't tell you how to do it in a few easy steps.

I'm going to close this, because it's not an issue with the video player.
