### ISSUE TITLE
Can't close the player

### ISSUE THREAD

**Issue by Pisoko** [nextcloud/files_videoplayer#28]
### Expected behaviour
I can't close the player while or after playing a video.
There is no "x" or something else to close. I have to F5 the nextcloudpage to continue my work.

### Steps to reproduce
1. Install nextcloud 12
2. play a Video  (Chrome / Firefox)

Greets from Germany

**Comment by Instagit** [comment]
[This has been reported](https://github.com/nextcloud/files_videoplayer/issues/25#issuecomment-304017382) and a fix should be on the way. :)
