### ISSUE TITLE
only plays webm and mp4 files, no avi or any other

### ISSUE THREAD

**Issue by mckaygerhard** [nextcloud/files_videoplayer#29]
#### Video doesn't play?

if the viceo player only plays html5 supported, added support for other formats..

### Expected behaviour
plya any format

### Actual behaviour
only html5 formats or webm and mp4

### Steps to reproduce
1. upload an avi file
2.play that file
3. no video

**Comment by Instagit** [comment]
This video player can only play video formats supported by the browser. AVI is not supported by any browser I think.

**Comment by horphi0815** [comment]
@Instagit : do you think, whether mts (sony) is possible?

BR
horphi

**Comment by Instagit** [comment]
@horphi0815: No, I don't think so. In any case you should expect problems, even if it works.

https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility
