### ISSUE TITLE
Cant close video window after upgrade to nc12

### ISSUE THREAD

**Issue by jsalatiel** [nextcloud/files_videoplayer#30]
## Expected behaviour
If i try to play some video from files app it should have a close button or close by pressing ESC.

### Actual behaviour
There is no way to get back to the file list, the video is over the window.
### Steps to reproduce
1. Play some video from the file app
2. There is no close button

**Comment by Instagit** [comment]
Hi jsalatiel,
this is already fixed (https://github.com/nextcloud/files_videoplayer/issues/25) and a patch will arrive with version 12.0.1. :)
