### ISSUE TITLE
No way to close video

### ISSUE THREAD

**Issue by nonplusnl** [nextcloud/files_videoplayer#34]
### Expected behaviour
When opening a video, I expected an 'X' somewhere in the upper right corner of the overlay window in order to close the video again. Keyboard ESC would do too. I believe this is how it was on Nextcloud <=11.

### Actual behaviour
Since upgrading to Nextcloud 12, the 'X' is gone (tried Opera, Chrome and Edge) and there is no way to close the video window. Even hitting 'back' in the browser doesn't help. Only reloading the entire page gets rid of the video window.

### Steps to reproduce
From Nextcloud files app, click on any video.

**Comment by Instagit** [comment]
Hi nonplusnl,
this has been fixed in 12.0.1, see https://github.com/nextcloud/files_videoplayer/issues/25.

I'll close this, but if you have any further problems after the update just re-open it.
