### ISSUE TITLE
Portrait videos don't play

### ISSUE THREAD

**Issue by nonplusnl** [nextcloud/files_videoplayer#35]
### Expected behaviour
'Portrait' videos (more vertical pixels than horizontal ones) should play in a custom-sized window.

### Actual behaviour
On 'portrait' videos, a standard landscape-sized window opens. The video appears to play, but the window stays black. Audio is played though.

### Steps to reproduce
Open a 'portrait' video from the files app in Nextcloud 12

**Comment by Instagit** [comment]
Yes, the video window is currently always 16:9 and I think changing that would make it difficult to keep it fully responsive. It would require detection of the video dimensions before playing and either fixed CSS for vertical videos or dynamic CSS for all possible video sizes. I'll put it on the list and consider it, but don't expect it any time soon.

However, the video should play. Please check if the video format is supported by your browser (you can drag it into an empty tab).
