### ISSUE TITLE
No close button

### ISSUE THREAD

**Issue by sysmoh** [nextcloud/files_videoplayer#36]
![video_player](https://user-images.githubusercontent.com/8458666/29003270-fa63e6a8-7ab3-11e7-95a1-8075f9edad6d.PNG)

### Expected behaviour
A close button should be present to close the video when playing

### Actual behaviour
No close button available, must refresh page to get rid of the video player
### Steps to reproduce
1. Go to nextcloud.com and start a free and quick trial of 60 minutes to test nextcloud
2. Click the Nextcloud.mp4 file to see it

Was running Windows 10 with chrome

**Comment by sosed213** [comment]
I have the same problem.

**Comment by Instagit** [comment]
This is fixed in 12.0.1. Please update or use the manual fix. :)

https://github.com/nextcloud/files_videoplayer/issues/25
