### ISSUE TITLE
Video rewind does not work.

### ISSUE THREAD

**Issue by sosed213** [nextcloud/files_videoplayer#37]
My details: (Crome browser, Nextcloud 12.1, Nginx 1.11.8 (cache purge), PHP 7.1.8).
I turn on the video mp4, playback starts. When you try to rewind, the video is reset and starts playback from the very beginning.

### Actual behaviour
The video should be played from the moment I place the cursor.

### Steps to reproduce
1. Download to Nexcloud 12.1 any mp4 video in the Chrome browser (on Nginx).
2. Press Playback.
3. Try to rewind.

(P.S. In Mozilla Firefox and Internet Explorer works fine.)

**Comment by sosed213** [comment]
I seem to have found a solution to the problem. With explicit disconnection of the caching for mp4, rewind has started. I do not know how much this is correct.

    location ~* \.(?:flv|mp4)$ {
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        include php_optimization.conf;
        fastcgi_pass php-handler;
        fastcgi_param HTTPS on;
        #fastcgi_cache_bypass $skip_cache;
        fastcgi_no_cache $skip_cache;
        #fastcgi_cache NEXTCLOUD12;
    }

**Comment by Instagit** [comment]
Thanks for reporting this. As you pointed out, it looks more like a problem with the video streaming than the player, but we can point users here when they run into similar problems.
