### ISSUE TITLE
add alias from quicktime to mp4

### ISSUE THREAD

**Issue by jmgurney** [nextcloud/files_videoplayer#46]
https://github.com/nextcloud/files_videoplayer/blob/8f09f7ff9e9064bece54a77a4fee0197713b52c7/js/viewer.js#L68

Can we get an alias added for video/quicktime to video/mp4?

The container is virtually identical, and, for example, Canon Cameras produce .MOV files, but they are able to be played as video/mp4 in Chrome, but Chrome refuses to play them when they are video/quicktime.

I attempted to add mov as video/mp4 to config/mimetypemapping.json of nextcloud, but this doesn't seem to do anything.  There is no documentation on commands that you have to run (https://docs.nextcloud.com/server/11/admin_manual/configuration_mimetypes/index.html#mimetype-mapping), but running `php occ maintenance:mimetype:update-db` does read the file, but does not write the new types anywhere.

**Comment by Instagit** [comment]
I'm pretty sure this could cause problems for browsers that natively support MOV files.

**Comment by Instagit** [comment]
I'm closing this for now. We could implement such a workaround/hack, but I want to be sure it doesn't cause problems.
