### ISSUE TITLE
Use videoplayer on public pages

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/files_videoplayer#48]
We should also use the video.js player from this app when a video is shared though a public link. No need to have a separate logic for presenting the video file in the server.

That would also fix https://github.com/nextcloud/server/issues/763

**Comment by Instagit** [comment]
Nice. I'll check it out as soon as I can. :)

**Comment by juliushaertl** [comment]
I've opened a PR for that at #52 :wink:
