### ISSUE TITLE
Create guide for optimal video streaming configuration

### ISSUE THREAD

**Issue by nsrosenqvist** [nextcloud/files_videoplayer#49]
It would be great if there could be a guide on how to configure nginx/apache to make the video streaming perform better. Right now I'm finding random guides that only cover pieces and I'm not experienced enough to piece it all together to a good configuration. I'm sure this would be really appreciated by users who have Nextcloud installed as a personal cloud for their families and don't necessarily have all the advanced knowledge of the server configuration.

**Comment by Instagit** [comment]
What exactly do you mean by "perform better". Web servers should be fine out of the box. There were some settings you'd have to change in the past, but that's more than two years ago and even then it was only required for Safari.

**Comment by nsrosenqvist** [comment]
When I was researching it many recommended configuring a nginx module called mp4 to allow for some more optimizations. Maybe that's not required and it performs well enough without it?

**Comment by Gymnae** [comment]
I'm kinda lost there as well. I thin earlier I was able to freely select a playing position, like skipping ahead, without the video having to buffer beforehand. Now I need to buffer it. Is that a server-side setting, or player based behavior?

**Comment by Instagit** [comment]
I think that is all webserver/PHP config, but I can't tell you the exact settings. The video player only requests a file. How the request is handled is up to the server.

**Comment by Gymnae** [comment]
@Instagit, I think so too. But for the life of me, or of google, I cannot find the correct parameters. Maybe it's nginx & php-fpm causing it. I also added the mp4 pseudo streaming module, but no change. It buffers completely before allowing choosing a play point.

**Comment by Instagit** [comment]
Yes, I also tried to find more information about this and was wondering why it's so poorly documented. While the default config should be fine, I'd still like to know how to change it.

As this is not an issue with the video player, but with the web server, I'll close this ticket, but if you find something, feel free to add it here. I'll do the same.

**Comment by worldwar345** [comment]
I would like to have any info on this too. Streaming video is very very slow, I mean the whole thing is slow, I have just about everything setup and optimized the way it should be with Redis file locking, memcache. Running on a reasonable fast laptop with fast internet, but only getting in the 1-2MB range with no answer other than the software itself is just poorly coded.

**Comment by riegercloud** [comment]
in nginx i am able to shift from position a to b without expensive buffering. just follow my guide: https://www.c-rieger.de/nextcloud-13-installation-guide

In the nextcloud.conf you will find a mp4-section regarding video_buffering.

Running an APACHE2 it is very slow and buffering the whole time.

**Comment by worldwar345** [comment]
Thank you Rieger, I appreciate the tutorials that you have been making they are very helpful.

**Comment by worldwar345** [comment]
I have no problem with being able to jump between points a to b within the video player, it’s more that the streaming is very slow and when it comes to downloading files (not just videos) that they are very slow. Downloading through things like google drive perform at download speeds that are very fast through my internet connection. And running speed tests on my internet connection speed shows that it is fast, but again when going through Nextcloud it is very slow. I would think that if that problem was solved then the video performance would also improve.

**Comment by Instagit** [comment]
@worldwar345 How is your server set up?

When I run Nextcloud locally, I get the full drive speed for downloads (500 MB/s) and videos buffer instantly, so there's nothing in Nextcloud itself or the video player that reduces the speed. That is with a default Apache server.

**Comment by Bellusterra** [comment]
Wow, That is Incredible. Yeah I see nothing close to that kind of speed. I have Nginx running rather than apache but I would not think that it would suffer that much because of that. I'm guessing the only limit to the speed from outside your network is your internet  bandwidth then?

**Comment by Bellusterra** [comment]
I found that the slow speed was coming from having a slow internet connection from my ISP.

**Comment by Nottt** [comment]
Having the same issue in a clean docker install, nextcloud version 16.

What is even more strange is that the video buffer even if the player has that grey thing :

![image](https://user-images.githubusercontent.com/13532436/57206250-c9097e00-6f9a-11e9-87c2-539e5a02e951.png)

**Comment by godfuture** [comment]
I would be interested as well. I have the nc apache docker install with nginx as reverse proxy. Streaming videos is just a pain.

**Comment by kylemart** [comment]
I have the same setup as godfuture, and streaming videos is also horribly non-performant... I don't have this issue when direct streaming via Plex...

**Comment by Bellusterra** [comment]
@Nottt your video may need to have the MOOV atom moved to the beginning of the video. It’s the file that tells the player all the info related to the video itself, handbrake is a useful tool for this. Or using the ffmpeg “-movflags faststart“ command. 

Reference:
https://stackoverflow.com/questions/15658895/is-there-a-downside-to-putting-the-moov-atom-at-the-beginning-of-an-mp4-file
