### ISSUE TITLE
Allow video playback of MKV

### ISSUE THREAD

**Issue by nsrosenqvist** [nextcloud/files_videoplayer#51]
Most of my video library are in MKV. I have the same codec settings that supported MP4 files have, would it be hard to implement support or do I really have to re-package all of my video library to have it supported by the videoplayer?

Related: https://github.com/nextcloud/files_videoplayer/issues/50

**Comment by Instagit** [comment]
>would it be hard to implement support

Nextcloud doesn't implement any codecs, we play whatever the browser supports.

We currently use a hack that allows many MKV files to be played, but the format is not officially supported. See https://github.com/nextcloud/files_videoplayer/issues/9.

I'm all for MKV support, but the right place to ask would be a feature request for Firefox or Chrome.

**Comment by nsrosenqvist** [comment]
Ok, sorry, I didn't see it had been discussed before. Feel free to close this.
