### ISSUE TITLE
Videos bigger than 2GiB do not play

### ISSUE THREAD

**Issue by karottenbaum** [nextcloud/files_videoplayer#55]
Hi, I'm assuming the file size is the problem here because smaller videos encoded with the same software at the same settings stream just fine.
In case you need information about the codecs used, I have included them below.

### Expected behaviour
Videos bigger than 2GiB play like usual

### Actual behaviour
Streaming videos bigger than 2GiB fails with the message "`The video could not be loaded, either because the server or network failed or because the format is not supported.`"
Downloading the file and playing it from the disk in Firefox works as expected, I couldn't stream it from Nextcloud as the file downloads automatically.

### Steps to reproduce
1. Upload video with a file size higher than 2 GiB
2. Attempt to stream it from Nextcloud

### Codec info

I'm attaching the (shortened) Codec info from VLC here:

```text
Stream 0
    Codec: H264 - MPEG-4 AVC (part 10) (avc1)
    Resolution: 720x578
    Frame rate: 25
Stream 1
    Codec: MPEG AAC Audio (mp4a)
    Channels: stereo
    Sample rate: 48000 Hz
Stream 2
    Codec: MPEG AAC Audio (mp4a)
    Sample rate: 48000 Hz
    Bits/sample: 16
    Bit rate: 1536 kB/s
Stream 3
    Codec: DVD Subtitles (spu )
Stream 4
    Codec: DVD Subtitles (spu )
Stream 5
    Codec: tx3g
```

**Comment by karottenbaum** [comment]
I've found an addon which intercepts the download link and forces the video to play in browser. Videos under 2GB play very fast, while videos over 2GB keep loading and are

**Comment by AncalagonTheBlack** [comment]
The Videos dont play and also lock up the server when you try it.

**Comment by Instagit** [comment]
I tried with a 4 GiB video file. No problems whatsoever. I guess it's a server configuration issue? I'm running an Apache server with default settings.

**Comment by karottenbaum** [comment]
My Apache is running on 32-bit, so that might be the problem. I'm not running any special configuration though, I think.

**Comment by Instagit** [comment]
Yeah, pretty sure that is the problem. PHP filesize() has a limit of 2 GB on 32-bit systems. There are ways around it, but using 32-bit for serious file servers is an edge case anyway.
