### ISSUE TITLE
Type error: link is undefined

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/files_videoplayer#58]
Basically https://sentry.io/share/issue/937b53339c9249bca7cdcbd590c962a1/

### Expected behaviour
No js errors

### Actual behaviour
```
Type error: link is undefined
```

### Steps to reproduce
1. Don't know, found it via Sentry https://sentry.io/share/issue/937b53339c9249bca7cdcbd590c962a1/

De-unified stack tracke:

1. https://github.com/nextcloud/files_videoplayer/blob/c7294b33c6f3f1bb1a0702d4e599a8bb7e0e8494/js/viewer.js#L15
2. https://github.com/nextcloud/server/blob/a3fdec7d4b45ed05f49660c05ee74ad11f32fe4a/core/js/js.js#L204-L213

`files_videoplayer` is installed and enabled on that instance.

**Comment by juliushaertl** [comment]
The only way I see how this could happen is that the javascript is still loaded even if the files_videoplayer app has been disabled. @ChristophWurst Did it happen again or was is a one-time issue?

**Comment by ChristophWurst** [comment]
I don't know. I found that on Sentry and now I can't even find the sentry ticket anymore :confused: 

Let's just assume this was fixed in the meantime ;)
