### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/files_videoplayer#6]
Some useful shortcuts from Youtube:
- `f` fullscreen
- `j` 10 seconds backward
- `k` or `space` trigger play/pause
- `l` 10 seconds forward
- `→` 5 seconds backward
- `←` 5 seconds forward
- `↑` volume up
- `↓` volume down

cc @Instagit @nextcloud/javascript

**Comment by Instagit** [comment]
I'll look into it when I have some time.

https://github.com/ctd1500/videojs-hotkeys

**Comment by Instagit** [comment]
I started working on this now and it should be fairly simple, but I'm running into problems when I try to load the plugin and I'm not sure if it's the script itself or the Nextcloud environment that causes them.

If anyone wants to look at it, I created a branch: https://github.com/nextcloud/files_videoplayer/commit/32f9013177717da16186742e25f4af8da5178909

**Comment by jancborchardt** [comment]
@Instagit just create a work-in-progress pull request of it, then it’s easier to review and collaborate :)

**Comment by jancborchardt** [comment]
Also cc @BernhardPosselt @Gomez since they know a bit more about keyboard shortcuts.

**Comment by Instagit** [comment]
Keyboard shortcuts will work once the video player replacement is finished (https://github.com/nextcloud/files_videoplayer/issues/20). The new player supports it by default, no need for plugins. It already works in the test branch, but the player needs to have focus.

**Comment by jancborchardt** [comment]
> but the player needs to have focus.

@Instagit cool, so I assume we’ll make sure it has focus when a video is playing? :)

**Comment by Instagit** [comment]
Yeah, I added that in this commit: https://github.com/nextcloud/files_videoplayer/commit/669a85e9a675c88194e60146f9ccf41aae62a65b. Keyboard shortcuts should be fully functional in the mediaelement branch.
