### ISSUE TITLE
Snap Installed Nextcloud 13.06 does not have Video Player in offered apps

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/files_videoplayer#62]
Snap Installed Nextcloud 13.06 does not have Video Player in offered apps

When I have attempted several times to manually add the files_videoplayer using the newest clone and making sure the file permissions matched the other working Nextcloud addon applications, the 'Enable' box is greyed out. My latest attempt resulted in a 'Remove' box in addition to the greyed out Enable.

I miss not being able to use the video player addon tool. Why is it missing in the latest snap installed Nextcloud?

Why is Nextcloud 13.06 not accepting the latest clone of the files_videoplayer?

**Comment by AaronADev** [comment]
@ASmith- I was actually wondering the same thing. I've been trying to get preview generation to work for mp4 files using the NextCloud snap but I haven't had any luck yet. You think this has anything to do with that? Might just be my ignorance, not sure yet.

**Comment by AaronADev** [comment]
@ASmith- Maybe it is my ignorance...is this the app that you were mentioning? It appears to be in the NextCloud Snap 14/Candidate (which has been working pretty well). Or is there another video player? 

I know a while back there used to be a different one but I dont know.

![capture](https://user-images.githubusercontent.com/12901914/46479397-8f7a5580-c7b4-11e8-87d8-4d47e0c27b06.PNG)

**Comment by rullzer** [comment]
This is caused by the snap not shipping it. Please report to the snap repo

**Comment by kyrofa** [comment]
Sorry folks, I missed the ping until the issue was closed :) . That said, I just took at look at the stable snap (which is v14 now) and the video player is definitely there and working.
