### ISSUE TITLE
files_videoplayer 1.3.0: Link to wrong repo

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/files_videoplayer#64]
Is linking to owncloud repo instead of nextcloud.

![videoplayer](https://user-images.githubusercontent.com/24833757/46405693-49b48300-c709-11e8-8ece-416a95c3c6c6.png)

**Comment by Instagit** [comment]
That is the app the player was originally based on so I think it would be ok to leave it as credit, but the link doesn't work anymore. I'll see if I can find a replacement or else we can remove it.

**Comment by Instagit** [comment]
Thanks. It was fixed at some point, so I'm closing this.
