### ISSUE TITLE
video player frezze video after fev seconds

### ISSUE THREAD

**Issue by Blisk** [nextcloud/files_videoplayer#72]
### Expected behaviour
When I play video it starts to play about second than it frezze and fev seconds nothing than again starts to play and again frezze.

### Actual behaviour
Video play all the time

### Steps to reproduce
1. play video
2.
3.
video player is 1.0, nextcloud is 14.0

**Comment by Blisk** [comment]
I have tested it again and now I see that high resolution gopro videos frezze all the time, until low resolution videos play ok withouht freezing.

**Comment by Instagit** [comment]
That seems like an issue on your side, but if you provide a video that doesn't work for you I'll look into it.

What you can try: Drag the video file into your browser so it's played in its own tab. When you get the same problems there, Nextcloud has nothing to do with it.

**Comment by Instagit** [comment]
I'm closing this issue for now, but if there is more info to suggest that it's in fact a problem with Nextcloud, feel free to reply.
