### ISSUE TITLE
Move to asynchronous loading

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/files_videoplayer#88]
We already load the videojs lib once needed, however due to the jquery dependency the main bundle still has around 91kb so we should either get rid of jquery here or add a separate script to handle the loading with OCP.Loader.loadScript.

**Comment by rullzer** [comment]
PR to kill jquery: https://github.com/nextcloud/files_videoplayer/pull/97

Main file is then 6.2Kb which is fine by me :smile:

**Comment by juliushaertl** [comment]
Let's close this then.
